// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1yLhpwmMLtcUI6FdTXo4ZA1LBxBeWDOM',
    appId: '1:325661041333:web:d72c68d9f6a565c86a14fc',
    messagingSenderId: '325661041333',
    projectId: 'traveler-46e31',
    authDomain: 'traveler-46e31.firebaseapp.com',
    storageBucket: 'traveler-46e31.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi1slykRF2g65QHPG5VCWHDsHX-aexjGc',
    appId: '1:325661041333:android:d03ba7f92570abc36a14fc',
    messagingSenderId: '325661041333',
    projectId: 'traveler-46e31',
    storageBucket: 'traveler-46e31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw7Syaztz7WwfawVhfnkRnD0xI4DW9UNE',
    appId: '1:325661041333:ios:6c38d70d239a0c376a14fc',
    messagingSenderId: '325661041333',
    projectId: 'traveler-46e31',
    storageBucket: 'traveler-46e31.appspot.com',
    iosBundleId: 'com.example.myBlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw7Syaztz7WwfawVhfnkRnD0xI4DW9UNE',
    appId: '1:325661041333:ios:4d26d0e7dd6f8dc96a14fc',
    messagingSenderId: '325661041333',
    projectId: 'traveler-46e31',
    storageBucket: 'traveler-46e31.appspot.com',
    iosBundleId: 'com.example.myBlog.RunnerTests',
  );
}
